# -*- coding: utf-8 -*-
"""Taller1_MathComp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16sEsmLSdAycZuixC1BeyhBxhtW6GbR-V
"""

while True:
  try:
    cantidad_a = int(input("Ingrese la cantidad de datos a registrar en el conjunto A "))
    break
  except ValueError:
    print('\n'"Debe ingresar un valor numérico")

conjunto_a = set()

for i in range (cantidad_a):
  while True:
    try:
      elemento_a = int(input("Ingrese un dato "))
      conjunto_a.add(elemento_a)
      break
    except ValueError:
      print('\n'"Debe ingresar un valor numérico")


print('\n'"Conjunto A:",conjunto_a)


while True:
  try:
    cantidad_b = int(input('\n'"Ingrese la cantidad de datos a registrar en el conjunto B "))
    break
  except ValueError:
    print('\n'"Debe ingresar un valor numérico")

conjunto_b = set()

for i in range (cantidad_b):
  while True:
    try:
      elemento_b = int(input("Ingrese un dato "))
      conjunto_b.add(elemento_b)
      break
    except ValueError:
      print('\n'"Debe ingresar un valor numérico")

print('\n'"Conjunto B:",conjunto_b)


print('\n'"¿Qué operación desea realizar?")
print('\n'"1. Unión",'\n'"2. Intersección",'\n'"3. Diferencia",'\n'"4. Diferencia simétrica")

while True:
  try:
    opcion = int(input('\n'"Tu opción es: "))
    if opcion >4 or opcion <1:
      print('\n'"Debe ingresar una opción valida")
    else: break
  except ValueError:
    print('\n'"Debe ingresar un valor numérico")

if opcion == 1 :
  union = conjunto_a.union(conjunto_b)
  c= len(union)
  print('\n'"La unión entre los conjuntos es: ", union, " su cardinalida es: ", c)

if opcion == 2 :
  inter = conjunto_a.intersection(conjunto_b)
  c= len(inter)
  print('\n'"La intersección entre los conjuntos es: ", inter, " su cardinalida es: ", c)

if opcion == 3 :
  dif = conjunto_a.difference(conjunto_b)
  c = len(dif)
  print('\n'"La diferencia entre los conjuntos es: ", dif, " su cardinalida es: ", c)

if opcion == 4 :
  difSim = conjunto_a.symmetric_difference(conjunto_b)
  c = len(difSim)
  print('\n'"La diferencia simétrica entre los conjuntos es: ", difSim, "su cardinalidad es: ", c)